### ISSUE TITLE
ACT hangs with FFXIV plugin v2.6.23

### ISSUE THREAD

**Issue by anthonypants** [goaaats/universalis_act_plugin#38]
The recent release of the FFXIV parsing plugin (https://github.com/ravahn/FFXIV_ACT_Plugin/releases/tag/2.6.2.3) appears to be incompatible with this plugin. After I update to 2.6.2.3 and restart ACT, it hangs on loading the Universalis plugin and will not start. The logs report that it is attempting to start the Universalis plugin. If I remove the Universalis .dll from the plugins folder and restart ACT, I am able to start ACT successfully.

Prior to installing this FFXIV parsing plugin update, I did not have issues with ACT failing to start, so I do not believe this issue is entirely due to the 6.0 Endwalker release.

**Comment by Swend5** [comment]
Same thing happening to me. Additionally it hangs when adding the dll through ACT.

**Comment by cfw34683** [comment]
this happens as well for me

**Comment by Quantization** [comment]
Yep, same issue here.

**Comment by cfw34683** [comment]
is there logs or anything we can provide to help fix this.. theres source code released 5 days ago but im not smart enough to compile it to dll.

**Comment by olanystrom** [comment]
I had to uninstalll the plugin, ACT just hangs on "loading plugin UniversalisPlugin"

**Comment by cfw34683** [comment]
9 hours ago a new version of the standalone was uploaded.. the message in the release gives me hope that they are working and not forgotten us.

**Comment by karashiiro** [comment]
I had to learn how to update the plugin so I could fix it, but I think I figured it out. Added to the v1.2 release, let me know if it works!

**Comment by karashiiro** [comment]
Officially fixed in v1.3, closing.

**Comment by ripsnortntear** [comment]
Thank you
